version: '3'
services:
  redis:
    image: redis:3
    ports:
      - 6379:6379
    volumes:
       - .redis/data:/data
       - .redis/redis.default.conf:/usr/local/etc/redis/redis.conf
      - ./:/repo
    command: /usr/local/etc/redis/redis.conf